/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    img: '/cappuccino.jpg',
    title: 'Cappuccino',
    price: '$5.20',
    starImg: 'Star_fill.svg',
    rating: '4.7',
    votes: '(65 votes)',
  },
  {
    img: '/cappuccino.jpg',
    title: 'House Coffee',
    price: '$3.50',
    starImg: 'Star_fill.svg',
    rating: '4.85',
    votes: '(14 votes)',
  },
  {
    img: '/cappuccino.jpg',
    title: 'Expresso',
    price: '$2.50',
    starImg: 'Star_fill.svg',
    rating: '4.9',
    votes: '(55 votes)',
  },
  {
    img: '/cappuccino.jpg',
    title: 'Coffee Latte',
    price: '$4.50',
    starImg: 'Star_fill.svg',
    rating: '5.0',
    votes: '(23 votes)',
  },
  {
    img: '/cappuccino.jpg',
    title: 'Chocolate Coffee',
    price: '$4.00',
    starImg: 'Star_fill.svg',
    rating: '4.65',
    votes: '(122 votes)',
    status: 'Sold Out',
  },
  {
    img: '/cappuccino.jpg',
    title: 'Valentine Special',
    price: '$5.50',
    starImg: '/Star.svg',
    votes: 'No ratings',
  },
];
